config/routes.rb
CricketManager::Application.routes.draw do
  resources :player_skins

  resources :matches

  resources :skins

  resources :players

  

end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :match_date, presence: true
  has_many :skins, dependent: :destroy
  has_many :player_skins, through: :skins
  has_many :players, through: :player_skins
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true
  has_many :player_skins
  has_many :skins, through: :player_skins
  has_many :matches, through: :skins
end

app/models/player_skin.rb
class PlayerSkin < ActiveRecord::Base
  validates :player_id, presence: true
  validates :skin_id, presence: true
  belongs_to :player
  belongs_to :skin
  has_one :match, through: :skin
end

app/models/skin.rb
class Skin < ActiveRecord::Base
  validates :match_id, presence: true
  belongs_to :match
  has_many :player_skins, dependent: :destroy
  has_many :players, through: :player_skins
  accepts_nested_attributes_for :player_skins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def new
    @match = Match.new
    @match.match_date = Time.now.to_date
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match
    else
      render 'new'
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      redirect_to @match
    else
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to matches_path
  end

  private
  def match_params
    params.require(:match).permit(:match_date)
  end
end

app/controllers/player_skins_controller.rb
class PlayerSkinsController < ApplicationController
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to @player
    else
      render 'new'
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path
  end

  private
  def player_params
    params.require(:player).permit(:name, :active)
  end
end

app/controllers/skins_controller.rb
class SkinsController < ApplicationController
  def index
    @skins = Skin.all
  end

  def new
    @skin = Skin.new
    2.times {@skin.player_skins.build}
  end

  def create
    @skin = Skin.new(skin_params)
    if @skin.save
      redirect_to @skin
    else
      render 'new'
    end
  end

  def show
    @skin = Skin.find(params[:id])
  end

  def edit
    @skin = Skin.find(params[:id])
  end

  def update
    @skin = Skin.find(params[:id])
    if @skin.update(skin_params)
      redirect_to @skin
    else
      render 'edit'
    end
  end

  def destroy
    @skin = Skin.find(params[:id])
    @skin.destroy
    redirect_to skins_path
  end

  private
  def skin_params
    params.require(:skin).permit(:match_id, player_skins_attributes: [
      :id, :player_id, :skin_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/player_skins_helper.rb
module PlayerSkinsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/skins_helper.rb
module SkinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CricketManager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matches/_form.html.erb
<%= form_for @match do |f| %>
  <% if @match.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@match.errors.count, "error") %> prohibited
      this match from being saved:</h2>
    <ul>
    <% @match.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :match_date %><br>
    <%= f.date_field :match_date %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/matches/edit.html.erb
<h1>Edit match</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<ul>
  <li><%= link_to "New", new_match_path %></li>
</ul>
 
<table>
  <tr>
    <th>Date</th>
  </tr>
 
  <% @matches.each do |match| %>
    <tr>
      <td><%= match.match_date %></td>
      <td>
        <%= link_to "Show", match_path(match) %>
        <%= link_to "Edit", edit_match_path(match) %>
        <%= link_to 'Destroy', match_path(match), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
</table>

app/views/matches/new.html.erb
<h1>New match</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @match.match_date %>
</p>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <% if @player.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@player.errors.count, "error") %> prohibited
      this player from being saved:</h2>
    <ul>
    <% @player.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/players/edit.html.erb
<h1>Edit player</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<ul>
  <li><%= link_to "New", new_player_path %></li>
</ul>
 
<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
  </tr>
 
  <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.active ? "yes" : "no" %></td>
      <td>
        <%= link_to "Show", player_path(player) %>
        <%= link_to "Edit", edit_player_path(player) %>
        <%= link_to 'Destroy', player_path(player), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<h1>New player</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>
 
<p>
  <strong>Active:</strong>
  <%= @player.active ? "Yes" : "No" %>
</p>

app/views/skins/_form.html.erb
<%= form_for @skin do |f| %>
  <% if @skin.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@skin.errors.count, "error") %> prohibited
      this skin from being saved:</h2>
    <ul>
    <% @skin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :match_id %><br>
    <%= f.select :match_id, options_from_collection_for_select(Match.order('match_date DESC'), :id, :match_date) %>
  </p>
  <ul>
    <%= f.fields_for :player_skins do |player_skins_form| %>
      <li>
        <%= player_skins_form.label :player_id %>
        <%= player_skins_form.select :player_id, options_from_collection_for_select(Player.order('name'), :id, :name) %>
      </li>
    <% end %>
  </ul>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/skins/edit.html.erb
<h1>Edit skin</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', skins_path %>

app/views/skins/index.html.erb
<h1>Listing skins</h1>

<ul>
  <li><%= link_to "New", new_skin_path %></li>
</ul>
 
<table>
  <tr>
    <th>Match</th>
    <th>Players</th>
  </tr>
 
  <% @skins.each do |skin| %>
    <tr>
      <td><%= skin.match.match_date %></td>
      <td></td>
      <td>
        <%= link_to "Show", skin_path(skin) %>
        <%= link_to "Edit", edit_skin_path(skin) %>
        <%= link_to 'Destroy', skin_path(skin), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
    </tr>
  <% end %>
</table>

app/views/skins/new.html.erb
<h1>New skin</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', skins_path %>

app/views/skins/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @skin.match.match_date %>
</p>
  <strong>Players:</strong>
  <ul>
  	<% @skin.players.each do |p| %>
  	<li><%= p.name %></li>
  	<% end %>
  </ul>
</p>